tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "denisidoro/tools"
# Manage your dotfiles across multiple machines, securely
brew "chezmoi"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Terminal-based visual file manager
brew "midnight-commander"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Terminal multiplexer
brew "tmux"
# UNIX shell (command interpreter)
brew "zsh"
# Command-line fuzzy finder written in Go
brew "fzf"
# Tracks most-used directories to make cd smarter
brew "z"
# Interactive cheatsheet tool for the command-line.
brew "denisidoro/tools/navi"
# Mac App Store command-line interface
brew "mas"
