tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "denisidoro/tools"
tap "buo/cask-upgrade"
# Manage your dotfiles across multiple machines, securely
# https://github.com/twpayne/chezmoi
brew "chezmoi"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Generic library support script
brew "libtool"
# Terminal-based visual file manager
# https://github.com/MidnightCommander/mc
brew "midnight-commander"
# Keep your Mac's application settings in sync
brew "mackup"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Terminal multiplexer
brew "tmux"
# UNIX shell (command interpreter)
# https://github.com/ohmyzsh/ohmyzsh
brew "zsh"
# Command-line fuzzy finder written in Go
brew "fzf"
# Tracks most-used directories to make cd smarter
brew "z"
# Interactive cheatsheet tool for the command-line.
brew "denisidoro/tools/navi"
# An archey script for OS X. archey -c
# https://obihann.github.io/archey-osx/
brew "archey"
# The cross-shell prompt for astronauts
# https://starship.rs/
brew "starship"
# --- Casks
# LibreOffice is free and open source software, originally based on OpenOffice.org
cask "libreoffice"
# https://www.mozilla.org/en-GB/firefox/
cask "firefox"
# https://www.google.com/intl/en_uk/chrome/
cask "google-chrome"
# https://github.com/gnachman/iTerm2
cask "iterm2"
# This is a tool for powerful automation of OS X.
# https://github.com/Hammerspoon/hammerspoon
cask "hammerspoon"
#
brew "reattach-to-user-namespace"
# CCleaner is the number-one tool for fixing a slow Mac
# https://www.ccleaner.com/ccleaner-mac
cask "ccleaner"
# Clipy is a Clipboard extension app for macOS.
# https://github.com/Clipy/Clipy
cask "clipy"
# With all of your communication and tools in one place
# https://slack.com/intl/en-gb/
cask "slack"
# MacoOS calendar
# https://www.mowglii.com/itsycal/
cask "itsycal"
# An open source note taking and to-do application
# https://github.com/laurent22/joplin
cask "joplin"
