#!/bin/bash
# https://raw.githubusercontent.com/ivankatliarchuk/dotfiles/master/shell/manage-python
# shellcheck disable=SC2034,SC2155,SC1090,SC2154,SC2154
#
# Set python latest version with pyenv
#

PYTHON_VERSIONS="$(pyenv versions | tr -d '[:space:]')"
PYENV_LATEST_VERSION="$(pyenv install --list | grep -v - | grep -v b | tail -1 | tr -d '[:space:]')"
export PYENV_GLOBAL_VERSION="$(pyenv version-name)"
export PYENV_VERSION="$(pyenv version-name)"

# Return if requirements are not found.
if (( ! $+commands[python] && ! $+commands[pyenv] )); then
  return 1
fi

if (( $+commands[pyenv] )); then
  eval "$(pyenv init - --no-rehash zsh)"
fi
