#!/bin/bash
# https://raw.githubusercontent.com/ivankatliarchuk/dotfiles/master/shell/manage-python
export PYTHON_VERSION=3.8.3
export PYENV_VERSION=${PYTHON_VERSION}

if [ -x "$(command -v pyenv)" ]; then
  if [ "$(python3 --version)" != "Python ${PYTHON_VERSION}" ]; then
    echo "install python version ${PYTHON_VERSION}"
    pyenv install --skip-existing "${PYTHON_VERSION}"
    pyenv global "${PYTHON_VERSION}"
  fi
  eval "$(pyenv init -)"
fi
