#!/bin/bash
# https://raw.githubusercontent.com/ivankatliarchuk/dotfiles/master/shell/profile
# Load .bashrc, which loads: ~/.{bash_prompt,aliases,functions,path,dockerfunc,extra,exports}
if [[ -r "${HOME}/.bashrc" ]]; then
	# shellcheck source=/dev/null
	source "${HOME}/.bashrc"
fi
# shellcheck source=/dev/null
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
