# https://dependabot.com/docs/config-file/
# https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#about-the-dependabotyml-file
# https://dependabot.com/docs/config-file/validator
# @todo: should be synced
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
    commit-message:
      prefix: chore
      include: "scope"
    reviewers:
      - ivankatliarchuk

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: "scope"
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
    reviewers:
      - ivankatliarchuk

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
    reviewers:
      - ivankatliarchuk
    commit-message:
      prefix: chore
      include: "scope"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: "scope"
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
    reviewers:
      - ivankatliarchuk

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: "scope"
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
    reviewers:
      - ivankatliarchuk

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: "scope"
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
    reviewers:
      - ivankatliarchuk
