# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github

repository:
  name: dotfiles
  description: "☘️ Sensible hacker defaults for macOS"
  topics: gitconfig, dotfiles, macos, bash, ivank, starship, dotbot, brew, iterm2, zsh, prezto
  homepage: https://github.com/ivankatliarchuk/dotfiles
  private: false
  has_projects: false
  has_wiki: false
  is_template: false
  has_downloads: false

branches:
  - name: master
