# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github

repository:
  name: dotfiles
  description: "👣 Sensible hacker defaults for macOS"
  topics: dotfiles, macos, bash, ivank, starship, dotbot, brew, iterm, zsh, prezto, gitconfig
  private: false

branches:
  - name: master
