---
session_name: tmuxp
windows:
- window_name: tmuxp
  focus: True
  layout: even-vertical
  options:
    main-pane-height: 35
  shell_command_before:
    - clear
  panes:
  - focus: true
  - pane
- window_name: docs
  layout: even-vertical
  options:
    main-pane-height: 35
  shell_command_before:
    - clear
  start_directory: ~/Documents/
  panes:
  - focus: true
  - pane
