---
session_name: tmuxp
windows:
- window_name: tmuxp
  focus: True
  layout: main-horizontal
  options:
    main-pane-height: 35
  panes:
  - focus: true
  - pane
- window_name: docs
  layout: main-horizontal
  options:
    main-pane-height: 35
  start_directory: ~/Documents/
  panes:
  - focus: true
  - pane
