---
session_name: 3p
windows:
  - window_name: logging for ${USER}
    layout: main-horizontal
    options:
      main-pane-height: 300
      automatic-rename: true
    panes:
      - focus: true
      - pane
      - start_directory: '~'
