---
session_name: 3p
windows:
  - window_name: logging for ${USER}
    layout: 5b88,157x36,0,0[157x22,0,0,1,157x13,0,23{77x13,0,23,2,79x13,78,23,3}]
    options:
      main-pane-height: 300
      automatic-rename: true
    panes:
      - focus: true
      - pane
      - start_directory: '~'
