---
session_name: 4p
windows:
  - window_name: 4-panes
    layout: 8130,159x39,0,0[159x26,0,0{104x26,0,0,1,54x26,105,0,2},159x12,0,27{74x12,0,27,3,84x12,75,27,4}]
    options:
      automatic-rename: true
    panes:
      - focus: true
      - pane
      - blank
      - shell_command:
          - clear
        start_directory: '~'

# .------------------.------------------.
# | (0)              | (1)              |
# |                  |                  |
# |                  |                  |
# |                  |                  |
# |------------------|------------------|
# | (2)              | (3)              |
# |                  |                  |
# |                  |                  |
# |                  |                  |
# '------------------'------------------'

# +---------------------+
# |       #             |
# |       #             |
# |       ##############|
# |       |       |     |
# |       |       |     |
# |---------------|     |
# |               |     |
# +---------------------+
