---
session_name: 4pv
windows:
  - window_name: vertical-panes
    layout: even-vertical
    options:
      automatic-rename: true
    panes:
      - focus: true           # pane no. 1
      - pane                  # pane no. 1
      - pane                  # pane no. 1
      - start_directory: '~'  # pane no. 1
