session_name: blank-pane
windows:
  - window_name: logging for ${USER}
    options:
      automatic-rename: true
    layout: 49f5,157x36,0,0{101x36,0,0,1,55x36,102,0[55x28,102,0,2,55x7,102,29,3]}
    panes:
      - focus: true
      - pane
      - pane
