session_name: blank-pane
start_directory: ${CURRENTPWD}
windows:
  - window_name: logging for ${USER}
    options:
      automatic-rename: true
    layout: main-vertical
    panes:
      - focus: true
      - start_directory: '~'
      - start_directory: '~'
