---
session_name: main
windows:
  - window_name: logging for ${USER}
    options:
      automatic-rename: true
    layout: fc1f,157x36,0,0{100x36,0,0,1,56x36,101,0[56x15,101,0,2,56x20,101,16,3]}
    panes:
      - focus: true
      - pane
      - shell_command:
        - clear
        start_directory: '~'
