#!/usr/bin/env bash
# https://raw.githubusercontent.com/ivankatliarchuk/dotfiles/master/tmux/aliases
#
# Shell/Tmux aliases.
#

# Pretty print the path
# shellcheck disable=SC2034,SC2139  # config_files used, just bash can get how
config_files=(~/.config/tmuxp/*.yaml)
for file in ${(M)config_files}; do
  filename=$(basename -- "$file")
  aliasname="${filename%.*}"
  alias "${aliasname}=tmuxp load ${aliasname} -a -y"
done
