prompt_order=[
  "directory", "line_break",
  "username", "line_break",
  "hostname", "line_break",
  "git_branch", "line_break",
  "character"
]

add_newline = false

[line_break]
disabled = true

[username]
disabled = true

[hostname]
ssh_only = true
disabled = false
