#
# Executes commands at login pre-zshrc.
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if command -v code; then
export EDITOR="code --wait"
else
export EDITOR='vim'
fi

export VISUAL='code'
export PAGER=''

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

[[ -f ~/.config/manage/python ]] && source ~/.config/manage/python

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
# export PYTHON_PATH="$(python3 -m site --user-base)/bin:$(python -m site --user-site)/bin:$PYTHONPATH"
# export PATH="$(pyenv root)/shims:$(command -v python3):$(command -v python):$PYTHON_PATH:$PATH"

path=(
  $path
  /usr/local/{bin,sbin}
  ~/.config/scripts
)
