#
# Executes commands at login pre-zshrc.
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='code'
export PAGER=''

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

export PATH=/usr/local/share/python:$PATH
#PYTHONPATH
export PYTHON_PATH="$(python3 -m site --user-site):$(python -m site --user-site):$PYTHONPATH"
export PATH=$PYTHON_PATH:$PATH

# Set the list of directories that Zsh searches for programs.
set -x
path=(
  $HOME/bin
  ~/dotfiles/bin
  /usr/local/{bin,sbin}
  $path
  $PYTHONPATH
)
