# Local config
[[ -f ~/.zshenv.local ]] && source ~/.zshenv.local

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#
export EDITOR="$(which code) --wait"
# if [[ -x $(which code) ]]; then
#   export EDITOR="$(which code) --wait"
# else
#   export EDITOR='vim'
# fi

export VISUAL='code'
export PAGER=''
# ruby environment variables
export RUBYOPT="-W0"
