name: release

on:
  push:
    branches:
      - master

env:
  DEFAULT_BUMP: patch
  INITIAL_VERSION: 0.1.0

jobs:
  artifact:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_firmware

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Print info
        run: |
          git rev-parse --short HEAD
          echo ${{ github.event.pull_request.base.sha }}
          git diff --name-only ${{ github.event.pull_request.base.sha }}...
          GIT_CHANGES=$(git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative ${{ github.event.pull_request.base.sha }}...)
          echo "$GIT_CHANGES"

      - name: define version
        id: register
        shell: 'bash {0}'
        run: |
          echo "::set-output name=release_timestamp::$(date +%Y-%m-%d_%H.%m)"
          echo "::set-output name=tag_hash::${GITHUB_SHA::8}"
          echo "::set-output name=changelog::$(git log -1 --pretty=format:"%s")"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.22.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        if: "!contains(github.event.head_commit.message, 'skip')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Release ${{ steps.register.outputs.release_timestamp }}
          draft: false
          prerelease: false
          body: |
            Changes in this Release ${{ steps.register.outputs.release_timestamp }}
            - ${{ steps.register.outputs.changelog }}
